### ISSUE TITLE
镜像的 supervisord.conf 启动命令导致 app_path函数不兼容

### ISSUE THREAD

**Issue by xuewlcn** [webman-tech/docker#1]
supervisord.conf 中的 
```
command=php /app/start.php start
```
导致 app_path函数输出的内容变为 `/app/app` ，这会导致很多问题，比如视图功能路径不正确！

判修复~

**Comment by krissss** [comment]
麻烦提供一下你是如何使用的

**Comment by xuewlcn** [comment]
是我的问题，我原本以为是路径识别。忘记了 docker 内的路径只是个映射...

Sorry ，这回复的速度点赞~
