### ISSUE TITLE
有没有方法限定php的版本

### ISSUE THREAD

**Issue by wxbacy** [webman-tech/docker#3]
php小版本8.1.x如果动态更新的话 可能会影响线上的稳定性

**Comment by krissss** [comment]
目前能想到的办法只有自己构建自己的镜像了，参考 [Dockerfile](https://github.com/webman-tech/docker/blob/main/Dockerfile)，修改前面的 PHP 版本

但是按道理原则上来说 php 第三位版本号应该不会影响稳定性，都是一些安全性更新

**Comment by wxbacy** [comment]
嗯

**Comment by wxbacy** [comment]
我自己制作镜像时，php-extension-installer安装扩展时很慢，最后connect fail了，这个必须要设置https proxy才能解决吧

**Comment by wxbacy** [comment]
![image](https://user-images.githubusercontent.com/20201380/193833999-78bcdf14-cc2b-467b-9600-7c01c1e984b8.png)

**Comment by krissss** [comment]
网络问题配置 proxy 应该可行
