### ISSUE TITLE
能否配置不运行在Debug模式

### ISSUE THREAD

**Issue by wxbacy** [webman-tech/docker#4]
如题，线上如果使用这个包部署的话

**Comment by wxbacy** [comment]
用supervisor.conf覆盖的话，加上-d参数会一直重启

**Comment by krissss** [comment]
不能，目前只能debug模式，docker 要求入口必须是一个前台进程，目前 workman 前台进程只有 debug 模式

**Comment by wxbacy** [comment]
get
