### ISSUE TITLE
最新版本更新了什么？

### ISSUE THREAD

**Issue by jackgoh** [webman-tech/docker#7]
gmp 代码报错后才发现在 Nov 24, 2024 at 10:36 am  在 dockerhub 发布了最新版本。可是没找到更新记录。

**Comment by krissss** [comment]
![image](https://github.com/user-attachments/assets/be54b2fd-9e50-4de5-992a-8cc4301892c9)

请问你用的是什么版本的，可以看下  actions 中的更新情况
